export { default as Admissions } from './Admissions';
export { default as AdmissionsHeader } from './AdmissionsHeader';
export { default as AdmissionTimeline } from './AdmissionTimeline';
export { default as AdmissionStepCard } from './AdmissionStepCard';
export { default as EligibilitySection } from './EligibilitySection';
export { default as RequiredDocuments } from './RequiredDocuments';
export { default as ScholarshipCard } from './ScholarshipCard';
export { default as AdmissionFAQPreview } from './AdmissionFAQPreview';
export { default as AdmissionCTA } from './AdmissionCTA';
export { admissionData } from './AdmissionData';
export { default } from './Admissions';
