export { default as Testimonials } from './Testimonials';
export { default as TestimonialsHeader } from './TestimonialsHeader';
export { default as TestimonialsSlider } from './TestimonialsSlider';
export { default as TestimonialCard } from './TestimonialCard';
export { default as VideoTestimonialCard } from './VideoTestimonialCard';
export { default as CommunityStats } from './CommunityStats';
export { default as TrustBadges } from './TrustBadges';
export { default as TestimonialsCTA } from './TestimonialsCTA';
export { testimonialsData } from './TestimonialsData';
export { default } from './Testimonials';
